### ISSUE TITLE
rename to "myBorder" to follow camel case 

### ISSUE THREAD

**Issue by AllusionMack** [dimi2u/dimitri-bariamis-1#4]
https://github.com/dimi2u/dimitri-bariamis-1/blob/4b5137f74aa582b3a3144d7b87032def2f2cbf62/checkers/index.html#L19

generally, we want to using some type of naming convention when introducing classes, ids and eventually (in javascript) variables.

Lets change `myborder` to be `myBorder`. I know, small difference. But having a convention **_matters._**

Read here for more on camel case: [https://www.theserverside.com/answer/Pascal-case-vs-camel-case-Whats-the-difference](https://www.theserverside.com/answer/Pascal-case-vs-camel-case-Whats-the-difference)

**Comment by dimi2u** [comment]
Thank you for letting me know this! I'm reading up on the camel case, much appreciated!
